In [92]:
import torch
torch.__version__

'2.9.1'

In [93]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [94]:
scalar.ndim

0

In [95]:
scalar.item()

7

In [96]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [97]:
vector.ndim

1

In [98]:
vector.shape

torch.Size([2])

In [99]:
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [100]:
MATRIX.ndim

2

In [101]:
MATRIX.shape

torch.Size([2, 2])

In [102]:
TENSOR = torch.tensor([[
    [1, 2, 3],
    [3, 6, 9],
    [2, 4, 5],
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [103]:
TENSOR.ndim

3

In [104]:
TENSOR.shape

torch.Size([1, 3, 3])

In [105]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[0.7499, 0.8104, 0.3947, 0.7605],
         [0.4452, 0.4805, 0.2640, 0.6174],
         [0.0383, 0.9263, 0.4040, 0.0496]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [106]:
random_image_size_tensor = torch.rand(size=(244,244, 3))
random_image_size_tensor, random_image_size_tensor.shape, random_image_size_tensor.ndim

(tensor([[[0.1685, 1.0000, 0.6643],
          [0.0942, 0.8791, 0.1715],
          [0.1770, 0.8501, 0.3674],
          ...,
          [0.1515, 0.7579, 0.4229],
          [0.8210, 0.4433, 0.5165],
          [0.3976, 0.4093, 0.4086]],
 
         [[0.3407, 0.7730, 0.1393],
          [0.0638, 0.1102, 0.6158],
          [0.1507, 0.5564, 0.0599],
          ...,
          [0.8533, 0.2141, 0.0367],
          [0.5185, 0.4069, 0.5871],
          [0.2474, 0.1507, 0.4824]],
 
         [[0.8562, 0.5552, 0.7575],
          [0.4031, 0.3281, 0.4723],
          [0.9981, 0.4980, 0.2487],
          ...,
          [0.0233, 0.8685, 0.4940],
          [0.2992, 0.3402, 0.5554],
          [0.1591, 0.9471, 0.4132]],
 
         ...,
 
         [[0.7349, 0.2560, 0.5827],
          [0.5637, 0.4519, 0.1764],
          [0.7168, 0.7118, 0.2535],
          ...,
          [0.1993, 0.4847, 0.7421],
          [0.2253, 0.6583, 0.4026],
          [0.7540, 0.2984, 0.1689]],
 
         [[0.7626, 0.6081, 0.9517],
          [0

In [107]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 2)

In [108]:
ones = torch.ones(size=(3, 4))
ones, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 2)

In [109]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
# Creates tensor similar to zero_to_ten tensor filled with zeroes 
ten_zeroes = torch.zeros_like(input=zero_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [111]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], 
    dtype=None, # Default is None, float32
    device=None, # Default is None, uses default tensor type
    requires_grad=False # if True, operations on tensor are recorded
)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device   

(torch.Size([3]), torch.float32, device(type='cpu'))

In [112]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [113]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.2380, 0.2627, 0.5913, 0.9015],
        [0.1056, 0.9133, 0.2694, 0.0327],
        [0.4993, 0.7807, 0.5113, 0.0326]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors 

In [114]:
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor * 10, tensor - 1

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([0, 1, 2]))

In [115]:
torch.mul(tensor, 2)

tensor([2, 4, 6])

In [116]:
tensor * tensor

tensor([1, 4, 9])

In [117]:
tensor = torch.tensor([1, 2, 3])
tensor.shape
tensor.matmul(tensor)

tensor(14)

In [118]:
tensor @ tensor

tensor(14)

In [119]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 223 μs, sys: 236 μs, total: 459 μs
Wall time: 284 μs


tensor(14)

In [120]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 77 μs, sys: 47 μs, total: 124 μs
Wall time: 93 μs


tensor(14)

In [121]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

# This doesn't work (invalid dimensions)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [ ]:
print(tensor_A)
print(tensor_B.T) # We can get transpose with .T getter 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)

print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])

Output shape: torch.Size([3, 3])


In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 

x = tensor_A.T
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([2, 3])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # Finding mean doesn't work without float values 
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
tensor = torch.rand(3, 2)
print(f"tensor: {tensor}")

print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

tensor: tensor([[0.7104, 0.9464],
        [0.7890, 0.2814],
        [0.7886, 0.5895]])
Index where max value occurs: 1
Index where min value occurs: 3


In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1, 7)
z, z.shape

z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [ ]:
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

# Note that permuting returns a view to the permuted data 

x_original, x_permuted

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


(tensor([[[0.3648, 0.1490, 0.8693],
          [0.0294, 0.5449, 0.0794],
          [0.2313, 0.2927, 0.3386],
          ...,
          [0.0142, 0.4286, 0.5314],
          [0.7014, 0.3068, 0.7550],
          [0.6155, 0.6846, 0.3695]],
 
         [[0.3440, 0.7202, 0.2682],
          [0.1106, 0.6911, 0.5973],
          [0.5016, 0.1312, 0.2875],
          ...,
          [0.7173, 0.5397, 0.4045],
          [0.2029, 0.2845, 0.4804],
          [0.6700, 0.9082, 0.9641]],
 
         [[0.1178, 0.2395, 0.7397],
          [0.2254, 0.5700, 0.0556],
          [0.7126, 0.5179, 0.6021],
          ...,
          [0.4928, 0.2287, 0.6585],
          [0.1298, 0.3462, 0.6858],
          [0.5218, 0.0802, 0.2934]],
 
         ...,
 
         [[0.5376, 0.5452, 0.0983],
          [0.6775, 0.8993, 0.0157],
          [0.8855, 0.3435, 0.8973],
          ...,
          [0.0225, 0.1665, 0.9601],
          [0.0972, 0.4044, 0.4718],
          [0.5772, 0.7063, 0.0263]],
 
         [[0.9301, 0.0844, 0.0296],
          [0

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Indexing goes outer dimention to inner
print(x[0])
print(x[0][0])
print(x[0][0][0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [ ]:
x[:, 0] # Take all 0 dimension values, and then 0'th index of second dimention

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [123]:
import numpy as np
import torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
tensor_f32 = torch.from_numpy(array).type(torch.float32)
array, tensor, tensor_f32

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [124]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [125]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")

random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1957, 0.7849, 0.8846, 0.9183],
        [0.6223, 0.3000, 0.1469, 0.4173],
        [0.5717, 0.3422, 0.5465, 0.5554]])

Tensor B:
tensor([[0.1178, 0.4902, 0.5368, 0.2026],
        [0.8510, 0.9423, 0.8376, 0.0532],
        [0.6732, 0.4649, 0.9704, 0.1899]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import random

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")

random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [135]:
torch.cuda.is_available()

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

device

'mps'

In [ ]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor_on_gpu = tensor.to("mps")
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

In [140]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])